### ISSUE TITLE
Tutorial Map

### ISSUE THREAD

**Issue by ghost** [NucleoidMC/Dungeons#4]
Basic premise:

- Investigate volcanic activity.
- Investigate "Weird Object" (beacon)
- Terrain collapses into cave (falling blocks textured as grass/dirt)
- Blindness to signify being knocked out.
- Zombies in the cave.
- User fights zombies, tutorial starts.

Underground the terrain is mega caves with gems and ores galore.

**Comment by Restioson** [comment]
What is the relations of the camping grounds and tutorial maps?

**Comment by diabolical17** [comment]
The premise is that the camping grounds could be the place where the player stays after and before they enter the dungeon, more or less a base they can build around. It could contain NPCs that sell stuff etc.

**Comment by ghost** [comment]
![](https://iili.io/KbjDps.png)
![](https://iili.io/Kbjpjf.png)
![](https://iili.io/KbjyQ4.png)
![](https://iili.io/KbwHCl.png)

**Comment by ghost** [comment]
![](https://iili.io/Kbwfyu.png)
